version: "3"

services:
  web:
    image: "<ACCT_NUMBER>.dkr.ecr.us-east-2.amazonaws.com/lamp/web:202209152248"
    restart: 'always'
    depends_on:
      - mysql
    restart: 'always'
    ports:
      - '80:80'
    links:
      - "mysql:database"
  mysql:
    image: "mysql:8.0.30"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
