version: "3"

services:
  web:
    image: "lamps:6"
    restart: 'always'
    depends_on:
      - mysql
    restart: 'always'
    ports:
      - '80:80'
    links:
      - "mysql:database"
  mysql:
    image: "mysql:8.0.30"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
